networks:
  shared_network:
    external: true

volumes:
  postgres_authdb:
  redis_data:
  kafka-data:

services:
  # Auth microservice
  app:
    image: msvc_auth:latest
    container_name: msvc_auth
    environment:
      AUTH_DB_URI: "postgres://test:test@auth_db:5432/auth?sslmode=disable"
      REDIS_URI: "auth_redis:6379"
      KAFKA_URI: "kafka:9092"
      MSVC_ACCESS_URI: "msvc_access:50051"
      PRIVATE_KEY_PATH: "/app/private.pem"
    ports:
      - "8081:8081"
    volumes:
      - /c/Users/win10/Documents/GitHub/oprosdom.ru/msvc_auth/private.pem:/app/private.pem:ro
    networks:
      - shared_network

  # Postgres DB
  auth_db:
    image: postgres:17-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_authdb:/var/lib/postgresql/data
    command: ["postgres", "-c", "ssl=off"]
    networks:
      - shared_network

  # Redis
  auth_redis:
    image: redis:8.2-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1"]
    networks:
      - shared_network

  # Kafka in KRaft mode
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    hostname: kafka
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - shared_network


  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - shared_network
