services:
  postgres-dev:  # Development-версия (без SSL)
    image: postgres:17-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #pg_hba тоже можно заменять
    command: ["postgres", "-c", "ssl=off"]

  redis:  # Добавленный Redis
    image: redis:8.2-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1"]  # Сохранять на диск каждые 60 сек при 1+ изменениях

volumes:
  postgres_data:
  redis_data:  # Том для Redis