networks:
  shared_network:
    external: true

services:
  app:
    image: msvc_codesender:latest
    container_name: msvc_codesender
    depends_on:
      - codesender_postgres
      - codesender_mongo
    environment:
      POSTGRES_DB_URI: "postgres://test:test@codesender_postgres:5432/notify?sslmode=disable"
      MONGO_DB_URI: "mongodb://admin:admin@codesender_mongo:27017"
      KAFKA_URI: "kafka:9092"
      #ZIMA_URL: "123" #нужно в k8s
      #ZIMA_KEY: "123" #нужно в k8s
      #ZIMA_DEVICE: "123" #нужно в k8s
    networks:
      - shared_network
  codesender_postgres:  # Development-версия (без SSL)
    image: postgres:17-alpine
    container_name: codesender_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: notify
    ports:
      - "5432:5432"
    volumes:
      - codesender_postgres:/var/lib/postgresql/data
      #pg_hba тоже можно заменять
    command: ["postgres", "-c", "ssl=off"]
    networks:
      - shared_network

  codesender_mongo:
    image: mongo:7.0
    container_name: codesender_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - codesender_mongo:/data/db
    networks:
      - shared_network

volumes:
  codesender_postgres:
  codesender_mongo: