services:
  postgres-dev:  # Development-версия (без SSL)
    image: postgres:17-alpine
    container_name: notify_postgres_dv
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: notify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_notify:/var/lib/postgresql/data
      #pg_hba тоже можно заменять
    command: ["postgres", "-c", "ssl=off"]

volumes:
  postgres_data_notify: