// Package auth Code generated by swaggo/swag. DO NOT EDIT
package auth

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/code": {
            "post": {
                "description": "Принимает JSON с телефоном (E.164) и кодом (uint32), UserAgent и IP сервер подставляет для логирования и валидации. При успешной проверке в ответе устанавливается HttpOnly cookie \"auth\" с JWT токеном.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка кода верификации и выдача JWT токена в куке",
                "parameters": [
                    {
                        "description": "Данные для проверки кода: телефон и код",
                        "name": "codeCheckReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UnsafeCodeCheckReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": \"Token issued in cookie\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "incorrect_request или codecheck_validation_failed при ошибках валидации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "codecheck_wrong_request или create_token_failed при ошибках сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/phone": {
            "post": {
                "description": "Принимает JSON с номером телефона (в формате E.164), UserAgent и IP заполняются сервером для лимитирования.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Отправка SMS с кодом верификации на телефон",
                "parameters": [
                    {
                        "description": "Данные для отправки кода на телефон. Только поле phone приходит от клиента",
                        "name": "phoneSendReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UnsafePhoneSendReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "incorrect_request или incorrect_phonesend при ошибках валидации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "phonesend_wrong_request при ошибках сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.UnsafeCodeCheckReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.UnsafePhoneSendReq": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/auth",
	Schemes:          []string{"http"},
	Title:            "AUTH API",
	Description:      "Аутентификация и выдача токенов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
