services:
  postgres-dev:  # Development-версия (без SSL)
    image: postgres:17-alpine
    container_name: users_postgres_dv
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #pg_hba тоже можно заменять
    command: ["postgres", "-c", "ssl=off"]

volumes:
  postgres_data: