services:
  postgres-dev:  # Development-версия (без SSL)
    image: postgres:17-alpine
    container_name: codesender_postgres_dv
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: notify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_codesender:/var/lib/postgresql/data
      #pg_hba тоже можно заменять
    command: ["postgres", "-c", "ssl=off"]
  mongodb:
    image: mongo:7.0
    container_name: my_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data_codesender:
  mongodb_data: