// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: msg_code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urgent        bool                   `protobuf:"varint,1,opt,name=urgent,proto3" json:"urgent,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // "sms" или "call"
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // формат e.194
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Retry         int32                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"` // какая это попытка отправки сообшения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCode) Reset() {
	*x = MsgCode{}
	mi := &file_msg_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCode) ProtoMessage() {}

func (x *MsgCode) ProtoReflect() protoreflect.Message {
	mi := &file_msg_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCode.ProtoReflect.Descriptor instead.
func (*MsgCode) Descriptor() ([]byte, []int) {
	return file_msg_code_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCode) GetUrgent() bool {
	if x != nil {
		return x.Urgent
	}
	return false
}

func (x *MsgCode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MsgCode) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MsgCode) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MsgCode) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

var File_msg_code_proto protoreflect.FileDescriptor

const file_msg_code_proto_rawDesc = "" +
	"\n" +
	"\x0emsg_code.proto\x12\x05proto\"\x88\x01\n" +
	"\aMsgCode\x12\x16\n" +
	"\x06urgent\x18\x01 \x01(\bR\x06urgent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x05R\x05retryB!Z\x1foprosdom.ru/shared/models/protob\x06proto3"

var (
	file_msg_code_proto_rawDescOnce sync.Once
	file_msg_code_proto_rawDescData []byte
)

func file_msg_code_proto_rawDescGZIP() []byte {
	file_msg_code_proto_rawDescOnce.Do(func() {
		file_msg_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_code_proto_rawDesc), len(file_msg_code_proto_rawDesc)))
	})
	return file_msg_code_proto_rawDescData
}

var file_msg_code_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msg_code_proto_goTypes = []any{
	(*MsgCode)(nil), // 0: proto.MsgCode
}
var file_msg_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_code_proto_init() }
func file_msg_code_proto_init() {
	if File_msg_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_code_proto_rawDesc), len(file_msg_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_code_proto_goTypes,
		DependencyIndexes: file_msg_code_proto_depIdxs,
		MessageInfos:      file_msg_code_proto_msgTypes,
	}.Build()
	File_msg_code_proto = out.File
	file_msg_code_proto_goTypes = nil
	file_msg_code_proto_depIdxs = nil
}
